discussion restyle
jamestjw/comp5531-w22-proj pull request #96
Opened 2022-04-22 20:10 UTC by chris7neves

2022-04-22 23:33 UTC, drouba reviewed
looks good to me

2022-04-23 01:09 UTC, jamestjw requested changes
To make the reply button work, change line 4 of discussion.js to 

```
 $(e.target).parent().find("form").toggle();
 ```

2022-04-23 01:09 UTC, jamestjw commented on public/discussion.php
> +            if (true) {
This is the code from the old version, the new version checks if the user has the permission to comment

2022-04-23 18:00 UTC, jamestjw approved these changes

2022-04-23 18:02 UTC, merged